version: '3'
services:
  php-fpm:
    build:
      context: php-fpm
    depends_on:
      - db
    volumes:
      - /home/nikita/docker-dostavka-lab/app:/var/www

  nginx:
    build:
      context: nginx
    volumes:
      - /home/nikita/docker-dostavka-lab/app:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites-available
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "9999:80"
      - "9998:443"

  db:
    build:
      context: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=testcase_dostavka_lab
      - MYSQL_USER=user_dostavka_lab
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=docker
#    volumes:
#          - /var/lib/mysql:/var/lib/mysql
#    volumes:
#          - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

